In [4]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
### help(np.array)

In [5]:
print(arr.shape,
arr.ndim,
arr.size,
arr.dtype)

(3, 3) 2 9 int64


In [8]:
print(np.zeros((3,3,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [28]:
print(np.ones((2,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
print(np.eye(3,3,-1))

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [38]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.linspace(0,6000,5)

array([   0., 1500., 3000., 4500., 6000.])

In [44]:
np.random.rand(3,3,3)

array([[[0.5760724 , 0.49074894, 0.23724385],
        [0.5312965 , 0.7875317 , 0.73713491],
        [0.95665145, 0.32391357, 0.47169904]],

       [[0.57621705, 0.99545777, 0.87012957],
        [0.3897389 , 0.03036024, 0.60381331],
        [0.29781142, 0.51116896, 0.45173676]],

       [[0.46127301, 0.74537653, 0.33976989],
        [0.77434046, 0.95714915, 0.10643574],
        [0.5439392 , 0.9111576 , 0.5802337 ]]])

In [59]:
np.random.randint(2,5,(7,2))

array([[2, 2],
       [2, 3],
       [4, 3],
       [3, 4],
       [3, 4],
       [2, 3],
       [3, 3]], dtype=int32)

In [67]:
arr2 = np.random.randint(3,7,(3,3))
arr + arr2

array([[ 6,  7,  6],
       [10,  8, 12],
       [12, 13, 14]])

In [71]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [75]:
print(np.mean(arr))
print(np.mean(arr, 0))
print(np.mean(arr, 1))

5.0
[4. 5. 6.]
[2. 5. 8.]


In [83]:
print(np.sum(arr, 0))
print(np.max(arr, 0))
np.std(arr, 0)

[12 15 18]
[7 8 9]


array([2.44948974, 2.44948974, 2.44948974])

In [85]:
print(arr[0],
arr[1:3],
arr[0,1],
arr[:,1])


[1 2 3] [[4 5 6]
 [7 8 9]] 2 [2 5 8]


In [8]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [11]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [14]:
help(np.matmul)

Help on ufunc in module numpy:

matmul = <ufunc 'matmul'>
    matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, axes, axis])

    Matrix product of two arrays.

    Parameters
    ----------
    x1, x2 : array_like
        Input arrays, scalars not allowed.
    out : ndarray, optional
        A location into which the result is stored. If provided, it must have
        a shape that matches the signature `(n,k),(k,m)->(n,m)`. If not
        provided or None, a freshly-allocated array is returned.
    **kwargs
        For other keyword-only arguments, see the
        :ref:`ufunc docs <ufuncs.kwargs>`.

    Returns
    -------
    y : ndarray
        The matrix product of the inputs.
        This is a scalar only when both x1, x2 are 1-d vectors.

    Raises
    ------
    ValueError
        If the last dimension of `x1` is not the same size as
        the second-to-last dimension of `x2`.

        If a scalar value is passed in.

    See A

In [16]:
np.linalg.det(arr)

np.float64(0.0)

In [ ]:
from urllib.parse import urlparse


hostname = 'www.google.com'
print(hostname.split('.'))

['www', 'google', 'com']
